services:
  db:
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=pba-headless
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pba-headless"]
      interval: 5s
      timeout: 5s
      retries: 6
