micronaut:
  application:
    name: pbaHeadless
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/styles/**"
        paths: "classpath:styles"
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://127.0.0.1:3000
            - http://localhost:3000
            - http://localhost:4200
  serde:
#    write-dates-as-timestamps: false # 1
    date-format: 'yyyy-MM-dd' #2

netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          db-type: postgres
          url: jdbc:postgresql://localhost:5431/pba-headless
          username: airbyte
          password: password
    reactive: true

airbyte:
  serverUrl: "https://api.airbyte.com/v1"
  apiKey: ${AIRBYTE_API_KEY}