micronaut:
  application:
    name: pbaHeadless
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/styles/**"
        paths: "classpath:styles"
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          db-type: postgres
          url: jdbc:postgresql://localhost:5431/pba-headless
          username: airbyte
          password: password
    reactive: true

